### ISSUE TITLE
How to recreate the diabetic retinopathy dataset?

### ISSUE THREAD

**Issue by nlml** [aakashrkaku/intermdiate_layer_matter_ssl#1]
Hi there,

It is unclear from your respository how exactly to recreate the training dataset for Diabetic Retinopathy used in your paper.

I downloaded the Diabetic Retinopathy dataset from Kaggle, then unzipped it and ran it through the script available [here](https://github.com/mikevoets/jama16-retina-replication/blob/master/eyepacs.sh) as it seems to me that this is what you have done.

I then get several different outputs from this script, and it seems the one you have used for training is that output to `/jama16-retina-replication/data/eyepacs/bin2`

However, when I run the above-mentioned script, the `bin2/validation` folder is empty. How exactly did you partition the training set into train and validation?

Thanks in advance!

**Comment by aakashrkaku** [comment]
Hi Liam,

Thank you for pointing this out. We used [this](https://github.com/mikevoets/jama16-retina-replication) to preprocess the dataset. Specifically, we followed steps 1, 2 and 3 given [here](https://github.com/mikevoets/jama16-retina-replication/blob/master/README.md) to preprocess the Eyepacs dataset.  We have also updated the readme to reflect this information. Please let us know if there are any further questions.

Thanks,
Aakash

Kind re

**Comment by nlml** [comment]
Thank you!

And how exactly did you split into training and validation? Just took a random 20% of train subject id's and put the associated (left + right) eye images into validation? This is what I have done.
