### ISSUE TITLE
About a lot of packages in requirements.txt

### ISSUE THREAD

**Issue by gskrpb** [aakashrkaku/intermdiate_layer_matter_ssl#3]
I tried to review your results, but a lot of packages in requirements.txt were loaded from files which I had no access to.
For example, 
`scipy @ file:///tmp/build/80754af9/scipy_1597686620742/work
seaborn @ file:///tmp/build/80754af9/seaborn_1600553570093/work
SecretStorage @ file:///tmp/build/80754af9/secretstorage_1594419219833/work`
Would you mind providing the versions of all the packages mentioned (and not mentioned) above? It would be really helpful.

**Comment by aakashrkaku** [comment]
Thank you for pointing it out. The requirements.txt files have been updated.
